### ISSUE TITLE
Return alternate profiles & mediatypes

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez-ui#14]

**Comment by jamiefeiss** [comment]
This feature hasn't been implemented yet, renaming issue to reflect.

**Comment by jamiefeiss** [comment]
Expected behaviour from Prez v2.

The UI needs to return data from alternate profiles & mediatypes to the browser from the API.

e.g. https://<base_url>/v/vocab/<vocab_id>?_profile=vocpub&_mediatype=turtle should return a turtle format of the vocpub profile of a vocabulary.

The simplest solution would probably be a simple redirect to the API.

**Comment by rob-metalinkage** [comment]
Note that the _set_ of profiles supported may vary according to the "itemClass" in a register - i.e. different classes of objects would have different sets of profiles defined - for example dcat:Datasets should have a profile that exposes a provenance history view of the dataset we wouldn't calculate by default - but "spacePrez" may not require this per item...

so the configured views need to be inspected (not necessarily at run-time) and the list of alternates generated - and ideally this would be accessible for the redirect tool of choice to use or convert into a configuration. 

(I've been managing these aspects separately and its a real pain to keep in sync with a realistic number of different types of objects in a knowledge graph...)
